name: Test setup-gauche action

on: [ push, repository_dispatch ]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: shirok/setup-gauche@v3
    - name: Run gosh
      run: gosh -V

  test-linux-head:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: shirok/setup-gauche@main
      with:
        gauche-version: 'snapshot'
        test-gauche: true
        configure-options: '--with-slib=/opt'
    - name: Run gosh
      run: gosh -V

  test-osx12:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: shirok/setup-gauche@v3
    - name: Run gosh
      run: gosh -V

  test-osx12-head:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: shirok/setup-gauche@main
      with:
        gauche-version: 'snapshot'
        test-gauche: true
        configure-options: '--with-slib=/opt'
    - name: Run gosh
      run: gosh -V
