name: Test setup-gauche action

on: [ push ]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: shirok/setup-gauche@d0506670302f101cc5088aabf7f083b2869e1604
    - name: Run gosh
      run: gosh -V

  test-osx12:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: shirok/setup-gauche@d0506670302f101cc5088aabf7f083b2869e1604
    - name: Run gosh
      run: gosh -V
